# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='title',
            new_name='name',
        ),
    ]
